### PR TITLE
Handle paths with spaces by wrapping the path to quotes

### LINKED ISSUE #14: Handle spaces in paths when running the PowerShell scripts
I reported this to the felixrieseberg/ember-cli-windows-addon#5 but I made some effort today to solve that issue and turns out that the problem is with the `ember-cli-windows` bin itself.

[Line 16](https://github.com/felixrieseberg/ember-cli-windows/blob/master/bin/ember-cli-windows#L16) fails in the `bin` if the `scriptPath` includes spaces. I think that it's easily fixed by wrapping the path in single quotes as in [petetnt/ember-cli-windows/blob/master/bin/ember-cli-windows#L16](https://github.com/petetnt/ember-cli-windows/blob/master/bin/ember-cli-windows#L16)

```
var child = spawn('powershell.exe', ['-NoProfile', '-NoLogo', "'" + scriptPath + "'"),
```

edit: Actually the task wasn't that simple after all, it required quite a bit more work for it to function properly. The current variation is ugly, but seems to work correctly wrapping both the script path and the path to ignore:

```
var child = spawn('powershell.exe', ['-NoProfile', '-NoLogo', "& {& '"+ scriptPath + "'-path '" + dir + "'}"]), // jshint ignore:line

```

Any ideas on how to improve that are welcome, I am not that well versed in PowerShell.

### PR DESCRIPTION
**Pull request by petetnt**
Fixes #14 and felixrieseberg/ember-cli-windows-addon#5

### CODE REVIEW

**Comment by felixrieseberg** [comment]
Thanks a lot! I'll give this a quick run on all the Windows versions (you know, 7 - 10 RC bits) and probably merge right after.

**Comment by petetnt** [comment]
Actually scratch that, despite the script claiming

```
Windows Search configured!
Finished Search Configuration.
Windows Defender configured!
Finished Defender Configuration.
```

the actual scripts aren't run as the commands are just echoed to the shell. Running the actual commands with `&` doesn't work either. Investigating....

**Comment by petetnt** [comment]
Okay, this [commit](https://github.com/petetnt/ember-cli-windows/commit/a30777ec981f78caf455823886810a4490a1b597) sure isn't pretty but at least it seems to work correctly.

```
   var child = spawn('powershell.exe', ['-NoProfile', '-NoLogo', "& {& '"+ scriptPath + "'-path '" + dir + "'}"]), // jshint ignore:line
```

**Comment by felixrieseberg** [comment]
This looks good! Only one small thing: I think we need a space right before `-Path`.

**Comment by petetnt** [comment]
@felixrieseberg good catch, I must have eaten it up when cleaning up. Fixed in cdece5f039b796a5e6471e6601a27c4f43ff027d

**Comment by felixrieseberg** [comment]
Thanks!

**Pull request merged**
